# GitHub Pages configuration
# This enables Jekyll to render markdown files while keeping your index.html as the home page

# Enable Jekyll processing
markdown: kramdown
highlighter: rouge

# Don't process files that start with underscore
include: []

# Exclude certain files from processing
exclude:
  - README.md
  - .gitignore
  - .DS_Store

# Set the default layout (optional)
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"